var dir_90ccbedd30978fa304e0881c1341fa84 =
[
    [ "azteacher.cc", "azteacher_8cc.html", null ],
    [ "azteacher.h", "azteacher_8h.html", "azteacher_8h" ],
    [ "batchedteacherloader.cc", "batchedteacherloader_8cc.html", null ],
    [ "batchedteacherloader.h", "batchedteacherloader_8h.html", "batchedteacherloader_8h" ],
    [ "common.h", "common_8h.html", "common_8h" ],
    [ "featurebitboard.cc", "featurebitboard_8cc.html", "featurebitboard_8cc" ],
    [ "featurebitboard.h", "featurebitboard_8h.html", "featurebitboard_8h" ],
    [ "featureextractor.h", "featureextractor_8h.html", "featureextractor_8h" ],
    [ "featurestack.cc", "featurestack_8cc.html", "featurestack_8cc" ],
    [ "featurestack.h", "featurestack_8h.html", "featurestack_8h" ],
    [ "featuretype.h", "featuretype_8h.html", "featuretype_8h" ],
    [ "ka.cc", "ka_8cc.html", null ],
    [ "ka.h", "ka_8h.html", "ka_8h" ],
    [ "math.h", "math_8h.html", "math_8h" ],
    [ "p.cc", "p_8cc.html", null ],
    [ "p.h", "p_8h.html", "p_8h" ],
    [ "simpleteacher.cc", "simpleteacher_8cc.html", null ],
    [ "simpleteacher.h", "simpleteacher_8h.html", "simpleteacher_8h" ],
    [ "teacherloader.cc", "teacherloader_8cc.html", null ],
    [ "teacherloader.h", "teacherloader_8h.html", "teacherloader_8h" ],
    [ "teacherwriter.cc", "teacherwriter_8cc.html", null ],
    [ "teacherwriter.h", "teacherwriter_8h.html", "teacherwriter_8h" ],
    [ "utils.cc", "utils_8cc.html", null ],
    [ "utils.h", "utils_8h.html", "utils_8h" ]
];