name: build

on: [push]

jobs:
  library-build:
    strategy:
      matrix:
        os: [ubuntu-24.04, aarch64-apple-darwin]
        sse_flags: ['']
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: make library
      working-directory: ${{ env.working-directory }}
      run: make ${{ matrix.sse_flags }} libnshogi

  python-module-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        sse_flags: ['']
    env:
      working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: install pybind11
      run: pip3 install pybind11
    - name: make pythoon module
      working-directory: ${{ env.working-directory }}
      run: make ${{ matrix.sse_flags }} python
