name: build

on: [push]

jobs:
  library-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sse_flags: ['', 'SSE2=1', 'SSE41=1', 'SSE42=1', 'AVX=1', 'AVX2=1']
    env:
      working-directory: ./

    steps:
    - uses: actions/checkout@v2
    - name: make library
      working-directory: ${{ env.working-directory }}
      run: make ${{ matrix.sse_flags }} libnshogi

  python-module-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        sse_flags: ['', 'SSE2=1', 'SSE41=1', 'SSE42=1', 'AVX=1', 'AVX2=1']
    env:
      working-directory: ./

    steps:
    - uses: actions/checkout@v2
    - name: install pybind11
      run: pip3 install pybind11
    - name: make pythoon module
      working-directory: ${{ env.working-directory }}
      run: make ${{ matrix.sse_flags }} python
