name: test

on: [push]

jobs:
  runtest:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      working-directory: ./

    steps:
    - uses: actions/checkout@v4
    - name: Set environment variable
      if: ${{ matrix.os == 'macos-latest' }}
      run: echo 'SIMD=NEON' >> $GITHUB_ENV
    - name: Set environment variable
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      run: echo 'SIMD=AVX2' >> $GITHUB_ENV
    - name: install libraries
      if: runner.os == 'Linux'
      run: pip3 install pybind11 numpy
    - name: install libraries
      if: runner.os == 'macOS'
      run: brew install pybind11 numpy
    - name: make library
      working-directory: ${{ env.working-directory }}
      run: make $SIMD=1 libnshogi
    - name: install library
      working-directory: ${{ env.working-directory }}
      run: sudo make $SIMD=1 install
    - name: test the static library
      working-directory: ${{ env.working-directory }}
      run: make $SIMD=1 runtest-static
    - name: test the shared library
      working-directory: ${{ env.working-directory }}
      run: make $SIMD=1 runtest-shared
    - name: test Python library
      working-directory: ${{ env.working-directory }}
      run: make runtest-python
